# -*- coding: utf-8 -*-
"""Time  series forcasting air passenger

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15cY_AxOTGcKarTUNIVTAuALzcl3X66Vr
"""

# ===============================
# AIR PASSENGERS TIME SERIES PROJECT
# ===============================

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error

# -------------------------------
# Load Dataset
# -------------------------------
data = pd.read_csv("/content/airplane-passengers.csv")
print(data.head())

# Convert Month to datetime
data['Month'] = pd.to_datetime(data['Month'])
data.set_index('Month', inplace=True)

# -------------------------------
# Plot Original Time Series
# -------------------------------
plt.figure(figsize=(10,5))
plt.plot(data['Passengers'])
plt.title("Monthly Air Passengers")
plt.xlabel("Year")
plt.ylabel("Passengers")
plt.show()

# -------------------------------
# ADF Test (Stationarity Check)
# -------------------------------
adf_result = adfuller(data['Passengers'])
print("ADF Statistic:", adf_result[0])
print("p-value:", adf_result[1])

# -------------------------------
# Log Transformation
# -------------------------------
data['Log_Passengers'] = np.log(data['Passengers'])

# -------------------------------
# Differencing
# -------------------------------
data['Diff_Log'] = data['Log_Passengers'].diff()
data.dropna(inplace=True)

# Re-check stationarity
adf_result_diff = adfuller(data['Diff_Log'])
print("ADF Statistic After Differencing:", adf_result_diff[0])
print("p-value After Differencing:", adf_result_diff[1])

# -------------------------------
# SARIMA Model Training
# -------------------------------
model = SARIMAX(
    data['Log_Passengers'],
    order=(1,1,1),
    seasonal_order=(1,1,1,12)
)

results = model.fit()
print(results.summary())

# -------------------------------
# Forecast Future Values
# -------------------------------
forecast_steps = 24
forecast = results.get_forecast(steps=forecast_steps)
forecast_mean = forecast.predicted_mean

# Convert back to original scale
forecast_mean = np.exp(forecast_mean)

# -------------------------------
# Plot Forecast
# -------------------------------
plt.figure(figsize=(10,5))
plt.plot(data['Passengers'], label="Actual")
plt.plot(forecast_mean, label="Forecast", color="red")
plt.title("Air Passengers Forecast")
plt.xlabel("Year")
plt.ylabel("Passengers")
plt.legend()
plt.show()

# -------------------------------
# Model Evaluation (MAE)
# -------------------------------
actual = data['Passengers'][-forecast_steps:]
predicted = forecast_mean[:len(actual)]

mae = mean_absolute_error(actual, predicted)
print("Mean Absolute Error (MAE):", mae)

"""# New Section"""